### ISSUE TITLE
Matching constructor causes a crash

### ISSUE THREAD

**Issue by bradphelan** [googleprojectzero/weggli#44] opened 2022-02-09 11:47 UTC
I have this code

```
int getX() { return 0; }

class Foo {
	

	Foo(int x, int y);

	int getX();
	int getY(){return m_y;};

	int m_x;
	int m_y;
};

int Foo::getX() const { return m_x; }

Foo::Foo(int x, int y)
	:m_x(x)
	,m_y(y)
	{}

```

but when I do this query

```
Foo::Foo(_){_;}
```

I get the following crash

```
thread '<unnamed>' panicked at 'begin <= end (166 <= 165) when slicing `
int getX() { return 0; }

class Foo {


        Foo(int x, int y);

        int getX();
        int getY(){return m_y;};

        int m_x;
        int m_y;
};

int Foo::getX() const { return m_x; }

Foo::Foo(int x, int y)
        :m_x(x)
        ,m_y(y)
        {}
`', /home/brad/.cargo/registry/src/github.com-1ecc6299db9ec823/weggli-0.2.3/src/result.rs:79:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bradphelan** [comment] 2022-02-09 11:49
If I move the constructor back into the class then I don't get a match or crash

```
int getX() { return 0; }

class Foo {
	

	Foo(int x, int y)
		:m_x(x)
		,m_y(y)
		{}

	int getX();
	int getY(){return m_y;};

	int m_x;
	int m_y;
};

int Foo::getX() const { return m_x; }

```

produces no match with the same query as before

```
Foo::Foo(_){_;}
```

**Comment by bradphelan** [comment] 2022-02-09 13:46
I've also tried 

```
$foo::$foo(_){_;}
```
to match all constructors and I think it matches but also crashes
```

**Comment by felixwilhelm** [comment] 2022-02-09 13:56
Thanks for the detailed bug report! 
I'm pretty sure that I know where the issue is. I'll take a look

**Comment by felixwilhelm** [comment] 2022-07-28 13:48
Sorry I forgot to ping this issue, but this should be fixed now. 

``` 
weggli -X 'Foo::Foo(_){}' /tmp/test.cpp
/tmp/test.cpp:17
Foo::Foo(int x, int y)
	:m_x(x)
..
	{}
```

**Closed by felixwilhelm** 2022-07-28 13:48 UTC
Labels: bug
